exclude: 'build|docs|node_modules|.cache|.git|.tox|.storybook/stories/assets|src/assets|((?:[^/]*/)*)(.svg)|((?:[^/]*/)*)(.xml)'
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3 # force all unspecified python hooks to run python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=10240']

  - repo: https://github.com/windpioneers/pre-commit-hooks
    rev: 0.0.5
    hooks:
      - id: check-branch-name
        args:
          # Main branch...
          - '^main$'
          # Or a descriptive kebab-case branch name
          #   which, if it includes an issue number, will
          #   auto-link pull requests to that issue on github, eg:
          #   my-branch-to-fix-issue-#6
          - '^([a-z][a-z0-9#/]*)(-[a-z0-9#]+)*$'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.2.1'
    hooks:
      - id: prettier

  - repo: https://github.com/octue/pre-commit-hooks
    rev: 0.9.0
    hooks:
      - id: check-commit-message-is-conventional
        stages: [commit-msg]
