export { default as BackgroundBox } from './BackgroundBox'
export { default as BasicPage } from './BasicPage'
export { default as CardPage } from './CardPage'
export { default as ErrorPage } from './ErrorPage'
export { default as Footer } from './Footer'
export { default as Fullscreenable } from './Fullscreenable'
export { default as Main } from './Main'
export { default as NavBar } from './NavBar'
