export const HEXGON_LARGE_OUTER_DIAMETER = 184
export const HEXGON_NORMAL_OUTER_DIAMETER = 132
export const HEXGON_SMALL_OUTER_DIAMETER = 82

export const HEXAGON_OUTER_DIAMETER_MAP = {
  large: HEXGON_LARGE_OUTER_DIAMETER,
  normal: HEXGON_NORMAL_OUTER_DIAMETER,
  small: HEXGON_SMALL_OUTER_DIAMETER,
}

export const HEXAGON_INNER_DIAMETER_MAP = {
  large: (Math.sqrt(3) * HEXGON_LARGE_OUTER_DIAMETER) / 2,
  normal: (Math.sqrt(3) * HEXGON_NORMAL_OUTER_DIAMETER) / 2,
  small: (Math.sqrt(3) * HEXGON_SMALL_OUTER_DIAMETER) / 2,
}

export const HEXAGON_DIAMETER_MAP = {
  outer: HEXAGON_OUTER_DIAMETER_MAP,
  inner: HEXAGON_INNER_DIAMETER_MAP,
}
