name: gcloud-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: deploy-contact
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: contact
          runtime: python38
          region: europe-west1
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          env_vars: MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }},MAILCHIMP_API_KEY=${{ secrets.MAILCHIMP_API_KEY }}
          source_dir: gcloud/functions

      - id: deploy-subscribe
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: subscribe
          runtime: python38
          region: europe-west1
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          env_vars: MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }},MAILCHIMP_API_KEY=${{ secrets.MAILCHIMP_API_KEY }}
          source_dir: gcloud/functions
